export default {
  SEARCH_STARTED: 'search/SEARCH_STARTED',
  SEARCH_SUCCEEDED: 'search/SEARCH_SUCCEEDED',
  SEARCH_FAILED: 'search/SEARCH_FAILED',
  LOAD_PAGE: 'search/LOAD_PAGE',
  SET_QUERY_TERM: 'search/SET_QUERY_TERM',
  SET_VIDEO_DURATION: 'search/SET_VIDEO_DURATION',
  ENTER: 'search/ENTER'
};
