export default {
  SEARCH_STARTED: 'search/SEARCH_STARTED',
  SEARCH_SUCCEEDED: 'search/SEARCH_SUCCEEDED',
  SEARCH_FAILED: 'search/SEARCH_FAILED',
  ENTER: 'search/ENTER',
  SET_QUERY_TERM: 'search/SET_QUERY_TERM',
  SET_VIDEO_DURATION: 'search/SET_VIDEO_DURATION',
  SET_PAGE_TOKEN: 'search/SET_PAGE_TOKEN'
};
